spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_USERPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: "server"

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days